const path = require("path");
const fs = require("fs");
const puppeteer = require("puppeteer");

async function main() {
  const inputFile = process.argv[2] || "index.html";
  const outputFile = process.argv[3] || "report.pdf";
  const normalizedInput = inputFile.replace(/\\/g, "/");
  const isPrescription = normalizedInput.includes("prescription/");
  const isInvoice = normalizedInput.includes("invoice/");

  const inputPath = path.resolve(process.cwd(), inputFile);
  const outputPath = path.resolve(process.cwd(), outputFile);
  const inputUrl = `file://${inputPath}`;
  const logoPath = path.resolve(process.cwd(), "svglogo.webp");
  const logoBase64 = fs.readFileSync(logoPath).toString("base64");
  const logoDataUri = `data:image/webp;base64,${logoBase64}`;

  const headerTemplate = `
    <style>
      html, body { margin: 0; padding: 0; }
    </style>
    <div style="width: 100%; height: 84px; background: #efeff1; border-bottom: 1px solid #d5d5d8; box-sizing: border-box; padding: 4px 15px; font-family: Arial, sans-serif;">
      <div style="display: flex; height: 100%; align-items: center; justify-content: space-between; gap: 16px;">
        <div style="display: flex; align-items: center; gap: 10px;">
          <img src="${logoDataUri}" style="width: 44px; height: 44px; object-fit: contain;" />
          <div>
            <div style="font-size: 24px; font-weight: 700; color: #2a7a76; line-height: 1.05;">Docnity</div>
            <div style="font-size: 20px; color: #4b5563; line-height: 1.05;">Health First Lab</div>
          </div>
        </div>
        <div style="text-align: right; color: #4b5563; font-size: 10px; line-height: 1.3; letter-spacing: 0.2px;">
          SF-1 - LH, HANUMAN ROAD (MAIN LAB)<br>
          ESKAY HOUSE, 54, HANUMAN ROAD, NEW DELHI - 110001<br>
          Ph: 011 - 39805710, Fax: 011 - 39805711
        </div>
      </div>
    </div>
  `;

  const footerTemplate = `
    <style>
      html, body { margin: 0; padding: 0; }
    </style>
    <div style="width: 100%; height: 90px; font-family: Arial, sans-serif; color: #2f2f33; box-sizing: border-box;">
      <div style="height: 66px; background: #e8e8ea; border-top: 1px solid #d5d5d8; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; font-size: 11px; line-height: 1.35; padding: 6px 10px 4px 10px; box-sizing: border-box;">
        <div>This report is intended for clinical correlation only. In case of any unusual or unexpected results, please consult your healthcare provider for further guidance.</div>
        <div>Report generated by Docnity. Certified and compliant with NABL &amp; quality assurance standards.</div>
      </div>
      <div style="height: 18px; background: #efeff0; border-top: 1px solid #d8d8db; display: flex; align-items: center; justify-content: center; font-size: 10px; line-height: 1; box-sizing: border-box;">
        Page <span class="pageNumber"></span> of <span class="totalPages"></span>
      </div>
    </div>
  `;

  const prescriptionHeaderTemplate = `
    <style>
      html, body { margin: 0; padding: 0; }
    </style>
    <div style="width: 100%; height: 74px; background: #ffffff; border-bottom: 1px solid #d5dbe3; box-sizing: border-box; padding: 6px 12px; font-family: Arial, sans-serif;">
      <div style="display: flex; height: 100%; align-items: center; justify-content: space-between; gap: 12px;">
        <div style="display: flex; align-items: center; gap: 9px;">
          <img src="${logoDataUri}" style="width: 34px; height: 34px; object-fit: contain;" />
          <div>
            <div style="font-size: 17px; font-weight: 700; color: #127f77; line-height: 1.05;">Docnity</div>
            <div style="font-size: 13px; color: #334155; line-height: 1.05;">Digital Care Clinic</div>
          </div>
        </div>
        <div style="text-align: right; color: #4b5563; font-size: 10px; line-height: 1.3;">
          Dr. Anjali Verma, MD (Internal Medicine)<br>
          Reg No: DMC/IM/45821 | Ph: +91-11-39805710
        </div>
      </div>
    </div>
  `;

  const prescriptionFooterTemplate = `
    <style>
      html, body { margin: 0; padding: 0; }
    </style>
    <div style="width: 100%; height: 46px; font-family: Arial, sans-serif; color: #475467; box-sizing: border-box;">
      <div style="height: 28px; border-top: 1px solid #d5dbe3; display: flex; align-items: center; justify-content: center; font-size: 9px; padding: 2px 8px; box-sizing: border-box;">
        Digitally generated prescription. Valid as per applicable e-prescription guidelines.
      </div>
      <div style="height: 18px; background: #f7f8fa; border-top: 1px solid #e0e4ea; display: flex; align-items: center; justify-content: center; font-size: 10px; line-height: 1; box-sizing: border-box;">
        Page <span class="pageNumber"></span> of <span class="totalPages"></span>
      </div>
    </div>
  `;

  const invoiceHeaderTemplate = `
    <style>
      html, body { margin: 0; padding: 0; }
    </style>
    <div style="width: 100%; height: 78px; background: #f8fafc; border-bottom: 1px solid #d9dde4; box-sizing: border-box; padding: 6px 12px; font-family: Arial, sans-serif;">
      <div style="display: flex; height: 100%; align-items: center; justify-content: space-between; gap: 12px;">
        <div style="display: flex; align-items: center; gap: 8px;">
          <img src="${logoDataUri}" style="width: 34px; height: 34px; object-fit: contain;" />
          <div>
            <div style="font-size: 17px; font-weight: 700; color: #127f77; line-height: 1.05;">Docnity</div>
            <div style="font-size: 13px; color: #334155; line-height: 1.05;">Invoice & Billing</div>
          </div>
        </div>
        <div style="text-align: right; color: #475467; font-size: 10px; line-height: 1.25;">
          Tax Invoice<br>
          Generated by Docnity Billing Engine
        </div>
      </div>
    </div>
  `;

  const invoiceFooterTemplate = `
    <style>
      html, body { margin: 0; padding: 0; }
    </style>
    <div style="width: 100%; height: 52px; font-family: Arial, sans-serif; color: #475467; box-sizing: border-box;">
      <div style="height: 34px; border-top: 1px solid #d9dde4; display: flex; align-items: center; justify-content: center; text-align: center; font-size: 9px; line-height: 1.2; padding: 3px 8px; box-sizing: border-box;">
        This is a computer-generated invoice and does not require a physical signature.
      </div>
      <div style="height: 18px; background: #f7f8fa; border-top: 1px solid #e0e4ea; display: flex; align-items: center; justify-content: center; font-size: 10px; line-height: 1; box-sizing: border-box;">
        Page <span class="pageNumber"></span> of <span class="totalPages"></span>
      </div>
    </div>
  `;

  const browser = await puppeteer.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.goto(inputUrl, { waitUntil: "networkidle0" });

    const pdfOptions = {
      path: outputPath,
      format: "A4",
      printBackground: true,
      preferCSSPageSize: false,
      displayHeaderFooter: true,
      margin: isPrescription
        ? {
            top: "34mm",
            bottom: "32mm",
            left: "4mm",
            right: "4mm"
          }
        : isInvoice
        ? {
            top: "34mm",
            bottom: "32mm",
            left: "4mm",
            right: "4mm"
          }
        : {
            top: "34mm",
            bottom: "32mm",
            left: "4mm",
            right: "4mm"
          }
    };

    if (isPrescription) {
      pdfOptions.headerTemplate = prescriptionHeaderTemplate;
      pdfOptions.footerTemplate = prescriptionFooterTemplate;
    } else if (isInvoice) {
      pdfOptions.headerTemplate = invoiceHeaderTemplate;
      pdfOptions.footerTemplate = invoiceFooterTemplate;
    } else {
      pdfOptions.headerTemplate = headerTemplate;
      pdfOptions.footerTemplate = footerTemplate;
    }

    await page.pdf(pdfOptions);

    console.log(`PDF generated: ${outputPath}`);
  } finally {
    await browser.close();
  }
}

main().catch((error) => {
  console.error("Failed to generate PDF:", error);
  process.exit(1);
});
